version: '3'
services:
  twelvet-mysql:
    container_name: twelvet-mysql
    restart: always
    image: twelvet-mysql
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=80M',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 123456

  twelvet-redis:
    container_name: twelvet-redis
    restart: always
    image: twelvet-redis
    privileged: true
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/twelvet/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/twelvet/redis/redis.conf

  twelvet-admin:
    container_name: twelvet-admin
    image: twelvet-admin
    restart: always
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    build:
      context: twelvet/twelvet-admin
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    # 允许使用外部网络
    networks:
      - frontend

networks:
  frontend:
    # 互通网络
    external: true